defmodule ExMachina.TestFactory do
  use ExMachina.Ecto, repo: ExMachina.TestRepo

  def custom_factory do
    %ExMachina.Custom{
      non_autogenerated_id: 1,
      name: "Testing"
    }
  end

  def user_factory do
    %ExMachina.User{
      name: "John Doe",
      admin: false,
      articles: [],
    }
  end

  def article_factory do
    %ExMachina.Article{
      title: "My Awesome Article",
      author: build(:user),
    }
  end

  def team_member_factory do
    %ExMachina.TeamMember{
      name: sequence("Member ")
    }
  end

  def team_factory do
    %ExMachina.Team{
      name: sequence("Team "),
      team_members: build_pair(:team_member)
    }
  end

  def company_factory do
    teams = build_pair(:team)

    %ExMachina.Company{
      teams: teams,
    }
  end

  def invalid_cast_factory do
    %ExMachina.InvalidCast{}
  end

  def user_map_factory do
    %{
      id: 3,
      name: "John Doe",
      admin: false
    }
  end
end
